// <auto-generated />
using System;
using DBetter.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBetter.Infrastructure.Migrations
{
    [DbContext(typeof(DBetterContext))]
    [Migration("20260124175121_RemoveClearedFlag")]
    partial class RemoveClearedFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBetter.Domain.ConnectionRequests.ConnectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ComfortClass")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EarlierReference")
                        .HasColumnType("text");

                    b.Property<string>("LaterReference")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ConnectionRequests", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Connections.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ConnectionDate")
                        .HasColumnType("date");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Connections", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.PassengerInformationManagement.PassengerInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("PassengerInformation", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Routes.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("JourneyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId")
                        .IsUnique();

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Stations.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EvaNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfoId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ril100")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber")
                        .IsUnique();

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("_passwordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DBetter.Infrastructure.OutboxPattern.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("DBetter.Domain.ConnectionRequests.ConnectionRequest", b =>
                {
                    b.OwnsMany("DBetter.Domain.ConnectionRequests.Entities.Passenger", "Passengers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("PassengerId");

                            b1.Property<Guid>("ConnectionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Age")
                                .HasColumnType("integer");

                            b1.Property<int>("Bikes")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Birthday")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Dogs")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<Guid?>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id", "ConnectionRequestId");

                            b1.HasIndex("ConnectionRequestId");

                            b1.ToTable("ConnectionRequestPassengers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConnectionRequestId");

                            b1.OwnsMany("DBetter.Domain.ConnectionRequests.ValueObjects.PassengerDiscount", "Discounts", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("PassengerId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ComfortClass")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id", "PassengerId", "ConnectionRequestId");

                                    b2.HasIndex("PassengerId", "ConnectionRequestId");

                                    b2.ToTable("ConnectionRequestPassengerDiscounts", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PassengerId", "ConnectionRequestId");
                                });

                            b1.Navigation("Discounts");
                        });

                    b.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.Route", "Route", b1 =>
                        {
                            b1.Property<Guid>("ConnectionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DestinationStationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxTransfers")
                                .HasColumnType("integer");

                            b1.Property<int>("MinTransferTime")
                                .HasColumnType("integer");

                            b1.Property<Guid>("OriginStationId")
                                .HasColumnType("uuid");

                            b1.HasKey("ConnectionRequestId");

                            b1.ToTable("ConnectionRequests");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionRequestId");

                            b1.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.Stopover", "FirstStopover", b2 =>
                                {
                                    b2.Property<Guid>("RouteConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("LengthOfStay")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("StationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RouteConnectionRequestId");

                                    b2.ToTable("ConnectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteConnectionRequestId");

                                    b2.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "MeansOfTransportNextSection", b3 =>
                                        {
                                            b3.Property<Guid>("StopoverRouteConnectionRequestId")
                                                .HasColumnType("uuid");

                                            b3.Property<bool>("Boats")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Busses")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("FastTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("HighSpeedTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("RegionalTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("SuburbanTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Trams")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("UndergroundTrains")
                                                .HasColumnType("boolean");

                                            b3.HasKey("StopoverRouteConnectionRequestId");

                                            b3.ToTable("ConnectionRequests");

                                            b3.WithOwner()
                                                .HasForeignKey("StopoverRouteConnectionRequestId");
                                        });

                                    b2.Navigation("MeansOfTransportNextSection")
                                        .IsRequired();
                                });

                            b1.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "MeansOfTransportFirstSection", b2 =>
                                {
                                    b2.Property<Guid>("RouteConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Boats")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("Busses")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("FastTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("HighSpeedTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("RegionalTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("SuburbanTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("Trams")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("UndergroundTrains")
                                        .HasColumnType("boolean");

                                    b2.HasKey("RouteConnectionRequestId");

                                    b2.ToTable("ConnectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteConnectionRequestId");
                                });

                            b1.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.Stopover", "SecondStopover", b2 =>
                                {
                                    b2.Property<Guid>("RouteConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("LengthOfStay")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("StationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RouteConnectionRequestId");

                                    b2.ToTable("ConnectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("RouteConnectionRequestId");

                                    b2.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "MeansOfTransportNextSection", b3 =>
                                        {
                                            b3.Property<Guid>("StopoverRouteConnectionRequestId")
                                                .HasColumnType("uuid");

                                            b3.Property<bool>("Boats")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Busses")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("FastTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("HighSpeedTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("RegionalTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("SuburbanTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Trams")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("UndergroundTrains")
                                                .HasColumnType("boolean");

                                            b3.HasKey("StopoverRouteConnectionRequestId");

                                            b3.ToTable("ConnectionRequests");

                                            b3.WithOwner()
                                                .HasForeignKey("StopoverRouteConnectionRequestId");
                                        });

                                    b2.Navigation("MeansOfTransportNextSection")
                                        .IsRequired();
                                });

                            b1.Navigation("FirstStopover");

                            b1.Navigation("MeansOfTransportFirstSection")
                                .IsRequired();

                            b1.Navigation("SecondStopover");
                        });

                    b.OwnsMany("DBetter.Domain.Connections.ValueObjects.ConnectionId", "SuggestedConnectionIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ConnectionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ConnectionId");

                            b1.HasKey("Id");

                            b1.HasIndex("ConnectionRequestId");

                            b1.ToTable("ConnectionRequestSuggestedConnectionIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConnectionRequestId");
                        });

                    b.Navigation("Passengers");

                    b.Navigation("Route")
                        .IsRequired();

                    b.Navigation("SuggestedConnectionIds");
                });

            modelBuilder.Entity("DBetter.Domain.Routes.Route", b =>
                {
                    b.OwnsMany("DBetter.Domain.Routes.Entities.RoutePassengerInformation", "PassengerInformation", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("FromStopIndex")
                                .HasColumnType("integer");

                            b1.Property<Guid>("InformationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ToStopIndex")
                                .HasColumnType("integer");

                            b1.HasKey("RouteId", "Id");

                            b1.ToTable("RoutePassengerInformation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("DBetter.Domain.Routes.ValueObjects.BikeCarriageInformation", "BikeCarriage", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("FromStopIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<int?>("ToStopIndex")
                                .HasColumnType("integer");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("DBetter.Domain.Routes.ValueObjects.CateringInformation", "Catering", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("FromStopIndex")
                                .HasColumnType("integer");

                            b1.Property<int?>("ToStopIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsOne("DBetter.Domain.Routes.ValueObjects.ServiceInformation", "ServiceInformation", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LineNumber")
                                .HasColumnType("text");

                            b1.Property<string>("ProductClass")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("ServiceNumber")
                                .HasColumnType("integer");

                            b1.Property<int>("TransportCategory")
                                .HasColumnType("integer");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.Navigation("BikeCarriage")
                        .IsRequired();

                    b.Navigation("Catering")
                        .IsRequired();

                    b.Navigation("PassengerInformation");

                    b.Navigation("ServiceInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("DBetter.Domain.Stations.Station", b =>
                {
                    b.OwnsOne("DBetter.Domain.Stations.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DBetter.Domain.Users.User", b =>
                {
                    b.OwnsMany("DBetter.Domain.Users.ValueObjects.Discount", "_discounts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("BoughtAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("ComfortClass")
                                .HasColumnType("integer");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ValidUntilUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("Discounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DBetter.Domain.Users.ValueObjects.RefreshToken", "_refreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("_discounts");

                    b.Navigation("_refreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
