// <auto-generated />
using System;
using DBetter.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBetter.Infrastructure.Migrations
{
    [DbContext(typeof(DBetterContext))]
    partial class DBetterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBetter.Domain.ConnectionRequests.ConnectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ComfortClass")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EarlierReference")
                        .HasColumnType("text");

                    b.Property<string>("LaterReference")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ConnectionRequests", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Connections.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ConnectionDate")
                        .HasColumnType("date");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Connections", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.PassengerInformationManagement.PassengerInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("PassengerInformation", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Routes.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainRunId")
                        .IsUnique();

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Stations.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EvaNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfoId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ril100")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaNumber")
                        .IsUnique();

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.TrainCompositions.TrainComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentUpdateInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainRun")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainRun")
                        .IsUnique();

                    b.ToTable("TrainCompositions", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_passwordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("_passwordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxAllowedCouplings")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("DBetter.Infrastructure.OutboxPattern.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("DBetter.Infrastructure.TrainCirculations.TrainCirculationPersistenceDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Identifier_DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Identifier_DestinationStationEva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Identifier_DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier_OriginStationEva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceInformation_LineNumber_Number")
                        .HasColumnType("text");

                    b.Property<string>("ServiceInformation_LineNumber_ProductClass")
                        .HasColumnType("text");

                    b.Property<int?>("ServiceInformation_ServiceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceInformation_TransportCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("TrainCirculations", (string)null);
                });

            modelBuilder.Entity("DBetter.Infrastructure.TrainRuns.TrainRunPersistenceDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BahnJourneyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BikeCarriage_FromStopIndex")
                        .HasColumnType("integer");

                    b.Property<int>("BikeCarriage_Status")
                        .HasColumnType("integer");

                    b.Property<int>("BikeCarriage_ToStopIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Catering_FromStopIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Catering_ToStopIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Catering_Type")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OperatingDay")
                        .HasColumnType("date");

                    b.Property<Guid>("TrainCirculationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainCirculationId", "OperatingDay")
                        .IsUnique();

                    b.ToTable("TrainRuns", (string)null);
                });

            modelBuilder.Entity("DBetter.Domain.ConnectionRequests.ConnectionRequest", b =>
                {
                    b.OwnsMany("DBetter.Domain.ConnectionRequests.Entities.Passenger", "Passengers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("PassengerId");

                            b1.Property<Guid>("ConnectionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Age")
                                .HasColumnType("integer");

                            b1.Property<int>("Bikes")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("Birthday")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Dogs")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<Guid?>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id", "ConnectionRequestId");

                            b1.HasIndex("ConnectionRequestId");

                            b1.ToTable("ConnectionRequestPassengers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConnectionRequestId");

                            b1.OwnsMany("DBetter.Domain.ConnectionRequests.ValueObjects.PassengerDiscount", "Discounts", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("PassengerId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ComfortClass")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id", "PassengerId", "ConnectionRequestId");

                                    b2.HasIndex("PassengerId", "ConnectionRequestId");

                                    b2.ToTable("ConnectionRequestPassengerDiscounts", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PassengerId", "ConnectionRequestId");
                                });

                            b1.Navigation("Discounts");
                        });

                    b.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.PlannedRoute", "PlannedRoute", b1 =>
                        {
                            b1.Property<Guid>("ConnectionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DestinationStationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxTransfers")
                                .HasColumnType("integer");

                            b1.Property<int>("MinTransferTime")
                                .HasColumnType("integer");

                            b1.Property<Guid>("OriginStationId")
                                .HasColumnType("uuid");

                            b1.HasKey("ConnectionRequestId");

                            b1.ToTable("ConnectionRequests");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionRequestId");

                            b1.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.Stopover", "FirstStopover", b2 =>
                                {
                                    b2.Property<Guid>("PlannedRouteConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("LengthOfStay")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("StationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("PlannedRouteConnectionRequestId");

                                    b2.ToTable("ConnectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedRouteConnectionRequestId");

                                    b2.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "MeansOfTransportNextSection", b3 =>
                                        {
                                            b3.Property<Guid>("StopoverPlannedRouteConnectionRequestId")
                                                .HasColumnType("uuid");

                                            b3.Property<bool>("Boats")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Busses")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("FastTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("HighSpeedTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("RegionalTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("SuburbanTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Trams")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("UndergroundTrains")
                                                .HasColumnType("boolean");

                                            b3.HasKey("StopoverPlannedRouteConnectionRequestId");

                                            b3.ToTable("ConnectionRequests");

                                            b3.WithOwner()
                                                .HasForeignKey("StopoverPlannedRouteConnectionRequestId");
                                        });

                                    b2.Navigation("MeansOfTransportNextSection")
                                        .IsRequired();
                                });

                            b1.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "MeansOfTransportFirstSection", b2 =>
                                {
                                    b2.Property<Guid>("PlannedRouteConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Boats")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("Busses")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("FastTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("HighSpeedTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("RegionalTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("SuburbanTrains")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("Trams")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("UndergroundTrains")
                                        .HasColumnType("boolean");

                                    b2.HasKey("PlannedRouteConnectionRequestId");

                                    b2.ToTable("ConnectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedRouteConnectionRequestId");
                                });

                            b1.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.Stopover", "SecondStopover", b2 =>
                                {
                                    b2.Property<Guid>("PlannedRouteConnectionRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("LengthOfStay")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("StationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("PlannedRouteConnectionRequestId");

                                    b2.ToTable("ConnectionRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedRouteConnectionRequestId");

                                    b2.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "MeansOfTransportNextSection", b3 =>
                                        {
                                            b3.Property<Guid>("StopoverPlannedRouteConnectionRequestId")
                                                .HasColumnType("uuid");

                                            b3.Property<bool>("Boats")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Busses")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("FastTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("HighSpeedTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("RegionalTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("SuburbanTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Trams")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("UndergroundTrains")
                                                .HasColumnType("boolean");

                                            b3.HasKey("StopoverPlannedRouteConnectionRequestId");

                                            b3.ToTable("ConnectionRequests");

                                            b3.WithOwner()
                                                .HasForeignKey("StopoverPlannedRouteConnectionRequestId");
                                        });

                                    b2.Navigation("MeansOfTransportNextSection")
                                        .IsRequired();
                                });

                            b1.Navigation("FirstStopover");

                            b1.Navigation("MeansOfTransportFirstSection")
                                .IsRequired();

                            b1.Navigation("SecondStopover");
                        });

                    b.OwnsMany("DBetter.Domain.Connections.ValueObjects.ConnectionId", "SuggestedConnectionIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ConnectionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ConnectionId");

                            b1.HasKey("Id");

                            b1.HasIndex("ConnectionRequestId");

                            b1.ToTable("ConnectionRequestSuggestedConnectionIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConnectionRequestId");
                        });

                    b.Navigation("Passengers");

                    b.Navigation("PlannedRoute")
                        .IsRequired();

                    b.Navigation("SuggestedConnectionIds");
                });

            modelBuilder.Entity("DBetter.Domain.Connections.Connection", b =>
                {
                    b.OwnsMany("DBetter.Domain.Connections.Entities.Transfer", "Transfers", b1 =>
                        {
                            b1.Property<Guid>("ConnectionId")
                                .HasColumnType("uuid");

                            b1.Property<byte>("Id")
                                .HasColumnType("smallint");

                            b1.HasKey("ConnectionId", "Id");

                            b1.ToTable("Transfers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConnectionId");

                            b1.OwnsOne("DBetter.Domain.Connections.ValueObjects.SubConnection", "FollowingSubConnection", b2 =>
                                {
                                    b2.Property<Guid>("TransferConnectionId")
                                        .HasColumnType("uuid");

                                    b2.Property<byte>("TransferId")
                                        .HasColumnType("smallint");

                                    b2.Property<DateTime>("ArrivalTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("DepartureTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("FromStationId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ToStationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("TransferConnectionId", "TransferId");

                                    b2.ToTable("Transfers");

                                    b2.WithOwner()
                                        .HasForeignKey("TransferConnectionId", "TransferId");

                                    b2.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "OriginalMeansOfTransport", b3 =>
                                        {
                                            b3.Property<Guid>("SubConnectionTransferConnectionId")
                                                .HasColumnType("uuid");

                                            b3.Property<byte>("SubConnectionTransferId")
                                                .HasColumnType("smallint");

                                            b3.Property<bool>("Boats")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Busses")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("FastTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("HighSpeedTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("RegionalTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("SuburbanTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Trams")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("UndergroundTrains")
                                                .HasColumnType("boolean");

                                            b3.HasKey("SubConnectionTransferConnectionId", "SubConnectionTransferId");

                                            b3.ToTable("Transfers");

                                            b3.WithOwner()
                                                .HasForeignKey("SubConnectionTransferConnectionId", "SubConnectionTransferId");
                                        });

                                    b2.Navigation("OriginalMeansOfTransport")
                                        .IsRequired();
                                });

                            b1.OwnsOne("DBetter.Domain.Connections.ValueObjects.SubConnection", "PreviousSubConnection", b2 =>
                                {
                                    b2.Property<Guid>("TransferConnectionId")
                                        .HasColumnType("uuid");

                                    b2.Property<byte>("TransferId")
                                        .HasColumnType("smallint");

                                    b2.Property<DateTime>("ArrivalTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("DepartureTime")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("FromStationId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("ToStationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("TransferConnectionId", "TransferId");

                                    b2.ToTable("Transfers");

                                    b2.WithOwner()
                                        .HasForeignKey("TransferConnectionId", "TransferId");

                                    b2.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "OriginalMeansOfTransport", b3 =>
                                        {
                                            b3.Property<Guid>("SubConnectionTransferConnectionId")
                                                .HasColumnType("uuid");

                                            b3.Property<byte>("SubConnectionTransferId")
                                                .HasColumnType("smallint");

                                            b3.Property<bool>("Boats")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Busses")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("FastTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("HighSpeedTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("RegionalTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("SuburbanTrains")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("Trams")
                                                .HasColumnType("boolean");

                                            b3.Property<bool>("UndergroundTrains")
                                                .HasColumnType("boolean");

                                            b3.HasKey("SubConnectionTransferConnectionId", "SubConnectionTransferId");

                                            b3.ToTable("Transfers");

                                            b3.WithOwner()
                                                .HasForeignKey("SubConnectionTransferConnectionId", "SubConnectionTransferId");
                                        });

                                    b2.Navigation("OriginalMeansOfTransport")
                                        .IsRequired();
                                });

                            b1.Navigation("FollowingSubConnection")
                                .IsRequired();

                            b1.Navigation("PreviousSubConnection")
                                .IsRequired();
                        });

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("DBetter.Domain.Routes.Route", b =>
                {
                    b.OwnsMany("DBetter.Domain.Routes.Stops.Stop", "Stops", b1 =>
                        {
                            b1.Property<short>("Id")
                                .HasColumnType("smallint");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("RouteIndex")
                                .HasColumnType("integer");

                            b1.Property<Guid>("StationId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id", "RouteId");

                            b1.HasIndex("RouteId");

                            b1.ToTable("RouteStops", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("DBetter.Domain.TrainRuns.ValueObjects.TravelTime", "ArrivalTime", b2 =>
                                {
                                    b2.Property<short>("StopId")
                                        .HasColumnType("smallint");

                                    b2.Property<Guid>("StopRouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("Planned")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime?>("Real")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("StopId", "StopRouteId");

                                    b2.ToTable("RouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId", "StopRouteId");
                                });

                            b1.OwnsOne("DBetter.Domain.TrainRuns.ValueObjects.TravelTime", "DepartureTime", b2 =>
                                {
                                    b2.Property<short>("StopId")
                                        .HasColumnType("smallint");

                                    b2.Property<Guid>("StopRouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("Planned")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime?>("Real")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("StopId", "StopRouteId");

                                    b2.ToTable("RouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId", "StopRouteId");
                                });

                            b1.OwnsOne("DBetter.Domain.Shared.Demand", "Demand", b2 =>
                                {
                                    b2.Property<short>("StopId")
                                        .HasColumnType("smallint");

                                    b2.Property<Guid>("StopRouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("FirstClass")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SecondClass")
                                        .HasColumnType("integer");

                                    b2.HasKey("StopId", "StopRouteId");

                                    b2.ToTable("RouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId", "StopRouteId");
                                });

                            b1.OwnsOne("DBetter.Domain.TrainRuns.ValueObjects.Platform", "Platform", b2 =>
                                {
                                    b2.Property<short>("StopId")
                                        .HasColumnType("smallint");

                                    b2.Property<Guid>("StopRouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Planned")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Real")
                                        .HasColumnType("text");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("StopId", "StopRouteId");

                                    b2.ToTable("RouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId", "StopRouteId");
                                });

                            b1.OwnsOne("DBetter.Domain.TrainRuns.ValueObjects.StopAttributes", "Attributes", b2 =>
                                {
                                    b2.Property<short>("StopId")
                                        .HasColumnType("smallint");

                                    b2.Property<Guid>("StopRouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("IsAdditional")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsCancelled")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsEntryOnly")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsExitOnly")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsRequestStop")
                                        .HasColumnType("boolean");

                                    b2.HasKey("StopId", "StopRouteId");

                                    b2.ToTable("RouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId", "StopRouteId");
                                });

                            b1.Navigation("ArrivalTime");

                            b1.Navigation("Attributes")
                                .IsRequired();

                            b1.Navigation("Demand")
                                .IsRequired();

                            b1.Navigation("DepartureTime");

                            b1.Navigation("Platform");
                        });

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("DBetter.Domain.Stations.Station", b =>
                {
                    b.OwnsOne("DBetter.Domain.ConnectionRequests.ValueObjects.MeansOfTransport", "AvailableMeansOfTransport", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Boats")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Busses")
                                .HasColumnType("boolean");

                            b1.Property<bool>("FastTrains")
                                .HasColumnType("boolean");

                            b1.Property<bool>("HighSpeedTrains")
                                .HasColumnType("boolean");

                            b1.Property<bool>("RegionalTrains")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SuburbanTrains")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Trams")
                                .HasColumnType("boolean");

                            b1.Property<bool>("UndergroundTrains")
                                .HasColumnType("boolean");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.OwnsOne("DBetter.Domain.Stations.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<Guid>("StationId")
                                .HasColumnType("uuid");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.HasKey("StationId");

                            b1.ToTable("Stations");

                            b1.WithOwner()
                                .HasForeignKey("StationId");
                        });

                    b.Navigation("AvailableMeansOfTransport");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DBetter.Domain.TrainCompositions.TrainComposition", b =>
                {
                    b.OwnsMany("DBetter.Domain.TrainCompositions.FormationVehicle", "Vehicles", b1 =>
                        {
                            b1.Property<Guid>("TrainCompositionId")
                                .HasColumnType("uuid");

                            b1.Property<byte>("Id")
                                .HasColumnType("smallint");

                            b1.Property<Guid>("FromStation")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ToStation")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.HasKey("TrainCompositionId", "Id");

                            b1.ToTable("FormationVehicles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TrainCompositionId");
                        });

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DBetter.Domain.Users.User", b =>
                {
                    b.OwnsMany("DBetter.Domain.Users.ValueObjects.Discount", "_discounts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("BoughtAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("ComfortClass")
                                .HasColumnType("integer");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ValidUntilUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("Discounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DBetter.Domain.Users.ValueObjects.RefreshToken", "_refreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("_discounts");

                    b.Navigation("_refreshToken");
                });

            modelBuilder.Entity("DBetter.Domain.Vehicles.Vehicle", b =>
                {
                    b.OwnsMany("DBetter.Domain.Vehicles.Coach", "CoachSequence", b1 =>
                        {
                            b1.Property<byte>("Id")
                                .HasColumnType("smallint");

                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CoachType")
                                .HasColumnType("text");

                            b1.Property<string>("ConstructionType")
                                .HasColumnType("text");

                            b1.HasKey("Id", "VehicleId");

                            b1.HasIndex("VehicleId");

                            b1.ToTable("VehicleCoaches", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("CoachSequence");
                });

            modelBuilder.Entity("DBetter.Infrastructure.TrainRuns.TrainRunPersistenceDto", b =>
                {
                    b.OwnsMany("DBetter.Infrastructure.TrainRuns.TrainRunPassengerInformationPersistenceDto", "PassengerInformation", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("FromStopIndex")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PassengerInformationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ToStopIndex")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TrainRunId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TrainRunId");

                            b1.HasIndex("Id", "TrainRunId")
                                .IsUnique();

                            b1.ToTable("TrainRunPassengerInformation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TrainRunId");
                        });

                    b.Navigation("PassengerInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
