name: Build container and deploy to DockerHub

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}/${{ vars.PACKAGE_OUTPUT_DIR }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Get Version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish Container
        env:
          SDK_CONTAINER_REGISTRY_UNAME: ${{ vars.DOCKERHUB_USERNAME }}
          SDK_CONTAINER_REGISTRY_PWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          dotnet publish ${{ vars.PROJECT_NAME }} \
          --configuration Release \
          --os linux \
          --arch x64 \
          /t:PublishContainer \
          -p:ContainerRegistry=registry-1.docker.io \
          -p:ContainerRepository=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.CONTAINER_NAME }} \
          -p:ContainerImageTags="${VERSION}"
